#!/usr/bin/env python3

# Generates the QFontAwesome icon constants and name tables from the Font Awesome metadata.
#
# QFontAwesome ships neither fonts nor generated headers: the application generates the headers from the
# Font Awesome download it ships (Free or Pro), commits them in its own repository and points the .pri at
# them with QFONTAWESOME_GENERATED_DIR. Re-run this script whenever the Font Awesome fonts are upgraded.
#
#   python3 build_headers.py [--fa-version X.Y.Z] <download>/metadata/icons.json <output-dir>
#
# It generates the following files in <output-dir>:
# - QFontAwesomeEnumGenerated.h    (fa::fa_* codepoint constants, FA version, FONT_AWESOME_PRO for Pro metadata)
# - QFontAwesomeStringGenerated.h  (icon name -> codepoint tables)
#
# The Font Awesome version is read from the fonts in <download>/otfs (the desktop download layout) unless
# --fa-version is given. QFontAwesome warns at runtime when a loaded font has a different version.
#
# Requires Python 3.7 or newer and nothing outside the standard library.
import argparse
import glob
import json
import os
import re
import struct
import sys


class Icons:
    def __init__(self, icon_file, fa_version):
        self.icons_common = {}
        self.icons_brands = {}
        self.icons_pro = {}
        self.icons_regular_free = {}
        self.fa_version = fa_version
        with open(icon_file, encoding='utf-8') as f:
            self.build_maps(json.load(f))

    # The Free metadata only lists free icons, so any icon without a free style means Pro metadata
    def is_pro(self):
        return bool(self.icons_pro)

    def tier_name(self):
        return 'Pro' if self.is_pro() else 'Free'

    def build_maps(self, icons):
        for key, data in icons.items():
            if data['free']:
                self.build_map_free(key, data)
            else:
                self.build_map_pro(key, data)

    def build_map_free(self, key, data):
        if data['free'][0] == 'brands':
            self.add_icon(self.icons_brands, key, data)
        else:
            if 'regular' in data['free']:
                self.add_icon(self.icons_regular_free, key, data)
            self.add_icon(self.icons_common, key, data)

    def build_map_pro(self, key, data):
        self.add_icon(self.icons_pro, key, data)

    @staticmethod
    def add_icon(icons, key, data):
        icons[key] = data['unicode']
        for alias_key in (data.get('aliases') or {}).get('names') or []:
            if alias_key in icons:
                sys.exit(f"Duplicate key found for alias {alias_key}!")
            icons[alias_key] = data['unicode']


def id_name(name):
    return 'fa_' + re.sub(r'[^a-z0-9_]', '_', name.lower())


def namespaced_id_name(name):
    return 'fa::' + id_name(name)


def string_name(name):
    return '"' + name.replace('"', '\\"') + '"'


# One line per item, comma separated, each line ending in a newline
def list_lines(lines):
    return ''.join(line + (',' if i < len(lines) - 1 else '') + '\n' for i, line in enumerate(lines))


def enum_block(enum_name, icons):
    entries = [f"    {id_name(name)} = 0x{unicode}" for name, unicode in icons.items()]
    return f"enum {enum_name} : uint16_t {{\n{list_lines(entries)}}};\n"


def name_array(array_name, icons):
    entries = [f"    {{ {string_name(name)}, {namespaced_id_name(name)} }}" for name in icons]
    return f"static const fa::QFontAwesomeNamedIcon {array_name}[] = {{\n{list_lines(entries)}}};\n"


def header_comment(icons):
    return (f"// Generated by QFontAwesome build_headers.py from the Font Awesome {icons.fa_version} "
            f"{icons.tier_name()} metadata. Do not edit.\n")


def generate_enum_header(icons):
    return (
        header_comment(icons)
        + "#ifndef QFONTAWESOMEENUMGENERATED_H\n"
        "#define QFONTAWESOMEENUMGENERATED_H\n"
        "\n"
        "/// The Font Awesome version these constants belong to; loading a font of another version logs a warning.\n"
        f"#define QFONTAWESOME_FA_VERSION \"{icons.fa_version}\"\n"
        "\n"
        "// The tier follows the metadata, not the build configuration\n"
        "#undef FONT_AWESOME_PRO\n"
        "#undef FONT_AWESOME_PRO_PLUS\n"
        + ("#define FONT_AWESOME_PRO 1\n" if icons.is_pro() else "")
        + "\n"
        "namespace fa {\n"
        + enum_block('fa_common_icons', icons.icons_common)
        + "\n\n"
        + enum_block('fa_brand_icons', icons.icons_brands)
        + ("\n" + enum_block('fa_pro_icons', icons.icons_pro) if icons.is_pro() else "")
        + "}\n"
        "\n"
        "#endif // QFONTAWESOMEENUMGENERATED_H\n"
    )


def generate_string_header(icons):
    if icons.is_pro():
        tier_array = name_array('faProIconArray', icons.icons_pro)
    else:
        tier_array = name_array('faRegularFreeIconArray', icons.icons_regular_free)
    return (
        header_comment(icons)
        + "// Included by QFontAwesome.cpp inside namespace fa.\n"
        "\n"
        + name_array('faCommonIconArray', icons.icons_common)
        + "\n"
        + name_array('faBrandsIconArray', icons.icons_brands)
        + "\n"
        + tier_array
    )


# Reads "Font Awesome version: X.Y.Z" from the version string (name ID 5) of an OpenType font
def font_version(path):
    try:
        with open(path, 'rb') as f:
            data = f.read()
        (num_tables,) = struct.unpack_from('>H', data, 4)
        name_offset = None
        for i in range(num_tables):
            tag, _checksum, offset, _length = struct.unpack_from('>4sIII', data, 12 + i * 16)
            if tag == b'name':
                name_offset = offset
        if name_offset is None:
            return None

        _format, count, strings_offset = struct.unpack_from('>3H', data, name_offset)
        for i in range(count):
            platform, _encoding, _language, name_id, length, offset = \
                struct.unpack_from('>6H', data, name_offset + 6 + i * 12)
            if name_id != 5 or platform not in (0, 3):
                continue

            start = name_offset + strings_offset + offset
            value = data[start:start + length].decode('utf-16-be')
            match = re.search(r'Font Awesome version: ([0-9][0-9A-Za-z.\-]*)', value)
            if match:
                return match.group(1)
        return None
    except (OSError, struct.error, UnicodeDecodeError):
        return None


def main():
    parser = argparse.ArgumentParser(description='Generates the QFontAwesome headers from the Font Awesome metadata.')
    parser.add_argument('--fa-version', metavar='VERSION',
                        help='Font Awesome version (default: read from <download>/otfs/*.otf)')
    parser.add_argument('icon_file', metavar='icons.json')
    parser.add_argument('output_path', metavar='output-dir')
    args = parser.parse_args()

    icon_file = args.icon_file
    output_path = args.output_path
    fa_version = args.fa_version
    if not os.path.isfile(icon_file):
        sys.exit(f"{icon_file} not found")

    if not fa_version:
        metadata_dir = os.path.dirname(icon_file) or '.'
        otfs = glob.glob(os.path.join(metadata_dir, '..', 'otfs', '*.otf'))
        versions = []
        for otf in otfs:
            version = font_version(otf)
            if version and version not in versions:
                versions.append(version)
        if len(versions) > 1:
            sys.exit(f"Fonts in {metadata_dir}/../otfs have different versions: {', '.join(versions)}")
        if not versions:
            sys.exit(f"Could not read the Font Awesome version from {metadata_dir}/../otfs; pass --fa-version")
        fa_version = versions[0]

    icons = Icons(icon_file, fa_version)
    os.makedirs(output_path, exist_ok=True)

    sources = {
        'QFontAwesomeEnumGenerated.h': generate_enum_header(icons),
        'QFontAwesomeStringGenerated.h': generate_string_header(icons),
    }
    for source_name, content in sources.items():
        # newline='\n' keeps LF line endings on Windows too
        with open(os.path.join(output_path, source_name), 'w', encoding='utf-8', newline='\n') as f:
            f.write(content)

    print(f"Generated Font Awesome {icons.fa_version} {icons.tier_name()} headers in {output_path} "
          f"({len(icons.icons_common)} common, {len(icons.icons_brands)} brands, {len(icons.icons_pro)} pro names)")


if __name__ == '__main__':
    main()
