# QFontAwesome provides:
#
# 1. The fonts it is licensed to use, in its own resources or on disk, loaded at runtime with
#    QFontAwesome::loadFonts().
# 2. The icon constants and name tables generated from the metadata of that same Font Awesome download:
#
#      python3 build_headers.py <download>/metadata/icons.json <app>/3rdparty/fontawesome/generated
#
#    committed in the application repository and selected before including this file:
#
#      QFONTAWESOME_GENERATED_DIR = $$PWD/3rdparty/fontawesome/generated
#      include(3rdparty/QFontAwesome/QFontAwesome/QFontAwesome.pri)

lessThan(QT_MAJOR_VERSION, 6) {
    error("QFontAwesome requires Qt 6")
}

isEmpty(QFONTAWESOME_GENERATED_DIR) {
    error("QFontAwesome: set QFONTAWESOME_GENERATED_DIR to the folder with the headers generated by build_headers.py before including QFontAwesome.pri")
}
QFONTAWESOME_GENERATED_DIR = $$absolute_path($$QFONTAWESOME_GENERATED_DIR, $$_PRO_FILE_PWD_)
!exists($$QFONTAWESOME_GENERATED_DIR/QFontAwesomeEnumGenerated.h)|!exists($$QFONTAWESOME_GENERATED_DIR/QFontAwesomeStringGenerated.h) {
    error("QFontAwesome: no generated headers in $$QFONTAWESOME_GENERATED_DIR; run build_headers.py")
}

CONFIG(fontAwesomeFree)|CONFIG(fontAwesomePro)|CONFIG(fontAwesomeProPlus) {
    !build_pass:warning("QFontAwesome: CONFIG fontAwesomeFree/Pro/ProPlus is no longer used; the tier follows the generated headers")
}

INCLUDEPATH += $$PWD $$QFONTAWESOME_GENERATED_DIR

SOURCES += $$PWD/QFontAwesome.cpp \
    $$PWD/QFontAwesomeAnim.cpp


HEADERS += $$PWD/QFontAwesome.h \
    $$PWD/QFontAwesomeAnim.h \
    $$QFONTAWESOME_GENERATED_DIR/QFontAwesomeEnumGenerated.h \
    $$QFONTAWESOME_GENERATED_DIR/QFontAwesomeStringGenerated.h
